<?php
/**
 * View for stored cards in my account
 *
 * @var \Payu\PaymentGateway\Block\Account\StoredCards $this
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php
$storedCards = $this->getStoredCards();
?>
<div class="block block-payu-cards payu__cards">
    <div class="block-content payu-cards__wrapper">
        <?php if (count($storedCards) > 0): ?>
            <div class="table-wrapper orders-recent">
                <table class="data table table-order-items recent" id="my-orders-table">
                    <caption class="table-caption"><?= $escaper->escapeHtml(__('Stored cards')); ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col"></th>
                        <th scope="col" class="col"><?= $escaper->escapeHtml(__('Card Number')); ?></th>
                        <th scope="col" class="col"><?= $escaper->escapeHtml(__('Card Expiration')); ?></th>
                        <th scope="col" class="col"><?= $escaper->escapeHtml(__('Action')); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php
                    /** @var \stdClass $card Stored Cards from REST API */
                    foreach ($storedCards as $card):
                        ?>
                        <tr class="card">
                            <td class="col card__logo">
                                <img src="<?= $escaper->escapeHtml($card->brandImageUrl); ?>"
                                     alt="<?= $escaper->escapeHtml($card->cardBrand); ?>"/>
                            </td>
                            <td class="col card__number"><?= $escaper->escapeHtml($card->cardNumberMasked); ?></td>
                            <td class="col card__expiration">
                                <?= $escaper->escapeHtml(
                                    $card->cardExpirationMonth . '/' . $card->cardExpirationYear
                                ); ?>
                            </td>
                            <td class="col card__action">
                                <form action="<?= $escaper->escapeHtml(
                                    $this->getUrl('customer/account/deletestoredcard/')
                                );
                                ?>" method="post">
                                    <?php echo $block->getBlockHtml('formkey') ?>
                                    <input name="card_id" type="hidden"
                                           value="<?= $escaper->escapeHtml($card->value); ?>"/>
                                    <button type="submit"><?= $escaper->escapeHtml(__('Remove card')); ?></button>
                                </form>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message info empty">
                <span>->escapeHtml(__('You don’t have any stored card.')); ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
