<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<?php /** @var \PayU\PaymentGateway\ViewModel\CreditWidgetViewModel $viewModel */ ?>
<?php /** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */ ?>
<?php
$viewModel = $block->getData('creditWidgetViewModel');
if ($viewModel->isWidgetEnabled('enable_for_minicart')) {
    $minicartCreditWidgetConfig = [
            'isActive' => true,
            'posId' => $viewModel->getPosId(),
            'key' => $viewModel->getKey(),
            'excludedPaytypes' => $viewModel->getExcludedPaytypes(),
            'lang' => $viewModel->getLanguageCode(),
            'currencyCode' => $viewModel->getCurrencyCode()
    ];
    $scriptContent = 'window.payuMinicartCreditWidgetConfig = ' . /* @noEscape */ json_encode($minicartCreditWidgetConfig);
    echo /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptContent, false);
}
?>